Repository NoticeMeDan/map, pull requests merged in 2018-05, with the labels that each got.

#78 Fix OsmDao array overflow issue + empty address searches
  src/main/java/com/noticemedan/mappr/dao/OsmDao.java
  src/main/java/com/noticemedan/mappr/model/DomainFacade.java
  src/main/java/com/noticemedan/mappr/viewmodel/SearchPaneController.java
Labels: bug, enhancement

#79 Dijkstra implemented in facade pattern structure.
  .editorconfig
  .gitignore
  .travis.yml
  LICENSE
  src/main/java/com/noticemedan/mappr/model/DomainFacade.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/Dijkstra.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/Network.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/NetworkParser.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/PathEdge.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/PathNode.java
  src/main/java/com/noticemedan/mappr/viewmodel/CanvasView.java
  src/main/java/com/noticemedan/mappr/viewmodel/MenuBarController.java
  src/main/resources/fxml/MenuBar.fxml
Labels: Requirements, enhancement

#81 OsmDao Fix
  src/main/java/com/noticemedan/mappr/dao/OsmDao.java
Labels: Requirements, bug

#82 Rapport
  docs/rapport/rapport.tex
Labels: Requirements

#88 Map Pane
  src/main/java/com/noticemedan/mappr/model/DomainFacade.java
  src/main/java/com/noticemedan/mappr/model/user/FavoritePoiManager.java
  src/main/java/com/noticemedan/mappr/view/MapInfo.java
  src/main/java/com/noticemedan/mappr/viewmodel/MainViewController.java
  src/main/java/com/noticemedan/mappr/viewmodel/MapCell.java
  src/main/java/com/noticemedan/mappr/viewmodel/MapCellController.java
  src/main/java/com/noticemedan/mappr/viewmodel/MapPaneController.java
  src/main/java/com/noticemedan/mappr/viewmodel/MenuBarController.java
  src/main/java/com/noticemedan/mappr/viewmodel/poi/FavoritePoiCell.java
  src/main/java/com/noticemedan/mappr/viewmodel/poi/FavoritePoiCellController.java
  src/main/java/com/noticemedan/mappr/viewmodel/poi/FavoritePoiPaneController.java
  src/main/java/com/noticemedan/mappr/viewmodel/poi/PoiBoxViewController.java
  src/main/resources/css/map-cell.css
  src/main/resources/css/map-pane.css
  src/main/resources/css/style.css
  src/main/resources/fxml/MainView.fxml
  src/main/resources/fxml/MapCell.fxml
  src/main/resources/fxml/MapPane.fxml
  src/main/resources/fxml/MenuBar.fxml
Labels: enhancement

#107 Free ram for everyone
  src/main/java/com/noticemedan/mappr/dao/OsmDao.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/PathEdge.java
  src/main/java/com/noticemedan/mappr/model/pathfinding/PathNode.java
  src/main/java/com/noticemedan/mappr/view/CanvasView.java
  src/main/java/com/noticemedan/mappr/viewmodel/MainViewController.java
  src/test/java/com/noticemedan/mappr/model/directions/ShortestPathTest.java
  src/test/java/com/noticemedan/mappr/model/kdtree/NearestNeighborTest.java
Labels: enhancement
